config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :entries, only: [:index, :new, :create] do
    # collection do
    #   get 'create', to: 'entries#create'
    #   post :create
    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_time_must_before_start_time, :start_time_cant_be_future, :time_overlapping

  private
  def end_time_must_before_start_time
    return unless time_changed?
    errors.add(:end_date, :before_start_time) if start_date > end_date
  end

  def time_changed?
    start_date_changed? || end_date_changed?
  end

  def start_time_cant_be_future
    errors.add(:base, :in_the_future) if start_date.to_date.beginning_of_day > Time.now.to_date.beginning_of_day
  end

  def time_overlapping
    errors.add(:base, :overlap) if Entry.where(start_date: start_date..end_date).
      or(Entry.where(end_date: start_date..end_date)).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from StandardError, :with => :rescue_standard_error

  private
  def rescue_standard_error(e)
    respond_to do |format|
      format.html { redirect_to "/500" }
      format.all  { render nothing: true, status: 500}
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = ActiveModel::ArraySerializer.new(
      Entry.all,
      each_serializer: Entries::EntrySerializer,
      root: false).
      as_json
  end

  def new
    @entries = Entry.new
  end

  def create
    @entries = Entry.new(entry_service.parse_timesheet_entry_info(entry_params))
    respond_to do |format|
      if @entries.save
        format.html  { redirect_to action: "index" }
      else
        format.html  { render :action => "new" }
      end
    end
  rescue ArgumentError => e
    render json: { error: e.message }, status: :bad_request
  end

  private
  def entry_params
    params.require(:entry).permit(:date, :start_time, :finish_time)
  end

  def entry_service
    return @entry_service if defined? @entry_service
    @entry_service = Entries::EntryService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="entry">
  <button type="button">
    <%= link_to t('entries.index.button.new'), :new_entry %>
  </button>
  <h2><%= t 'entries.index.title' %></h2>
  <% @entries.each do |entry| %>
    <table>
      <tr>
        <td>
          <p>
            <%= entry[:date] %><%= t 'entries.index.label.separator' %>
          </p>
        </td>
        <td>
          <p>
            <%= t 'entries.index.label.entry_date', start_time: entry[:start_time], end_time: entry[:end_time] %>
          </p>
        </td>
        <td>
          <p>
            <%= t 'entries.index.label.currency' %><%= entry[:price] %>
          </p>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="entry">
  <h2><%= t 'entries.new.title' %></h2>
  <%= form_for @entries, :url => entries_path do |f| %>
    <table>
      <tr>
        <td>
          <%= f.label t('entries.new.label.date') %>
        </td>
        <td>
          <%= date_field :entry, "date", required: true %>
        </td>
        <td>
          <% @entries.errors.full_messages_for(:base).each do |message| %>
            <div class="errors"><%= message %></div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label t('entries.new.label.start_time') %>
        </td>
        <td>
          <%= time_field :entry, "start_time", value: "%H:%M", required: true %>
        </td>
        <td>
          <% @entries.errors.full_messages_for(:start_date).each do |message| %>
            <div class="errors"><%= message %></div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label t('entries.new.label.finish_time') %>
        </td>
        <td>
          <%= time_field :entry, "finish_time", value: "%H:%M", include_seconds: false, required: true %>
        </td>
        <td>
          <% @entries.errors.full_messages_for(:end_date).each do |message| %>
            <div class="errors"><%= message.sub('date', 'time') %></div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.submit t('entries.new.button.new'), :id => 'submitEntry' %>
        </td>
      </tr>
    </table>
  <%- end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entryapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>